config/routes.rb
RecipeBox::Application.routes.draw do
  devise_for :users
  root to: 'pages#welcome'

  resources :recipes do
    resources :comments, shallow: true, except: [:new, :show, :index]
  end

  resources :users, only: :show do
    resources :tags, only: [:index, :create]
    resources :recipes, only: :index
  end

  resources :tags, only: [:show, :edit, :update, :destroy]

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :ingredients, presence: true
  validates :directions, presence: true

  has_many :comments, inverse_of: :recipe, dependent: :destroy
  has_many :recipe_tags, inverse_of: :recipe, dependent: :destroy
  has_many :tags, through: :recipe_tags
  belongs_to :user, inverse_of: :recipes

  before_save :calculate_time

  def self.maximum_time(minutes)
    Recipe.where("time_in_minutes <= ?", minutes).where("time_in_minutes IS NOT NULL")
  end

  def self.search_text(keywords)
    Recipe.where("to_tsvector(name || ' ' || ingredients || ' ' || directions) @@ plainto_tsquery(?)", keywords)
  end

  def self.filter_recipes(params)
    recipes = Recipe.all
    if params[:minutes].present?
      recipes = recipes.maximum_time(params[:minutes].to_i)
    end
    if params[:keywords].present?
      recipes = recipes.search_text(params[:keywords])
    end
    recipes
  end

  private

  def calculate_time
    if time_number.blank?
      self.time_in_minutes = nil
    else
      case time_unit
      when 'minutes'
        self.time_in_minutes = time_number.to_i
      when 'hours'
        self.time_in_minutes = (time_number.to_f * 60).round
      end
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:show, :index]

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @comments = @recipe.comments.order(:created_at)
    @comment = Comment.new
  end

  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @recipes = Recipe.where(user_id: params[:user_id]).filter_recipes(params)
    else
      @recipes = Recipe.filter_recipes(params)
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      flash[:notice] = 'Recipe was successfully added.'
      redirect_to recipe_path(@recipe)
    else
      flash.now[:alert] = 'There was an issue with your recipe. Please try again.'
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    authorize_user(@recipe)
  end

  def update
    @recipe = Recipe.find(params[:id])
    authorize_user(@recipe)

    if @recipe.update(recipe_params)
      flash[:notice] = 'Recipe was successfully updated.'
      redirect_to recipe_path(@recipe)
    else
      flash.now[:alert] = 'There was an issue with your recipe. Please try again.'
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    authorize_user(@recipe)

    @recipe.destroy
    flash[:notice] = 'Recipe was successfully deleted.'
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :time_number, :time_unit, :servings,
      :ingredients, :directions, :notes, :visibility, tag_ids: [])
  end

  def authorize_user(recipe)
    unless user_signed_in? and (recipe.user == current_user)
      raise ActionController::RoutingError.new('The page you requested was not found.')
    end
  end
end

app/views/recipes/_form.html.erb
<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h3>

    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @recipe do |f| %>

  <div class="input">
    <%= f.label :name, 'Name (required)' %>
    <%= f.text_field :name %>
  </div>
  <div class="input">
    <%= f.label :ingredients, 'Ingredients (required)' %>
    <%= f.text_area :ingredients, cols: 60, rows: 6 %>
  </div>
  <div class="input">
    <%= f.label :directions, 'Directions (required)' %>
    <%= f.text_area :directions, cols: 60, rows: 6 %>
  </div>
  <div class="input">
    <%= f.label :notes %>
    <%= f.text_field :notes %>
  </div>
  <div class="row">
    <div class="medium-3 large-2 columns">
      <div class="input">
        <%= f.label :time_number, 'Time' %>
        <%= f.text_field :time_number %>
      </div>
    </div>
    <div class="medium-3 large-2 columns">
      <div class="input">
        <%= f.label :time_unit, 'Unit' %>
        <%= f.select :time_unit, ['minutes', 'hours'] %>
      </div>
    </div>
    <div class="medium-6 large-4 columns">
      <div class="input">
        <%= f.label :servings %>
        <%= f.text_field :servings %>
      </div>
    </div>
  </div>
  <% unless Tag.count == 0 %>
    <div class="input">
      <%= f.label :tag_ids, 'Tags' %>
      <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %>
    </div>
  <% end %>
  <div class="submit">
    <%= f.submit class: "button small" %>
  </div>
</div>

<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<% if @user %>
  <h1><%= @user.username %>'s Recipes</h1>
  <p>Recipes posted by <%= link_to @user.username, user_path(@user) %>:</p>
<% else %>
  <h1>All Recipes</h1>
<% end %>

<%= form_tag(recipes_path, method: :get) do %>
  <%= field_set_tag do %>
    <div class="row">
      <div class="medium-8 large-9 columns">
        <%= label_tag 'keywords' %>
        <%= text_field_tag 'keywords', params[:keywords], placeholder: 'Search recipe name, ingredients, and directions' %>
        </div>
        <div class="medium-4 large-3 columns">
          <%= label_tag 'minutes', 'Maximum Time (minutes)' %>
          <%= text_field_tag 'minutes', params[:minutes], size: 4 %>
      </div>
    </div>
    <div class="row">
      <div class="medium-8 large-5 medium-centered columns">
        <div id="recipe-search-buttons">
          <ul class="button-group">
            <li><%= submit_tag 'Search Recipes', class: "button small" %></li>
            <li><input id="clear-form" class="button small" type="button" value="Clear Form"></li>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<% @recipes.each do |recipe| %>
  <p><%= link_to recipe.name, recipe_path(recipe) %></p>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<div id="recipe-intro-container">
  <div class="row">
    <div class="medium-5 columns">
      <p>posted by <%= link_to @recipe.user.username, user_path(@recipe.user) %> on <%= @recipe.created_at.strftime("%F") %></p>
    </div>
    <div class="medium-7 columns">
      <div class="row">
        <% unless @recipe.time_in_minutes.blank? %>
          <div class="medium-4 columns">
            <p>Time: <%= @recipe.time_number %>
              <% if @recipe.time_number == '1' %>
                <%= @recipe.time_unit.singularize %>
              <% else %>
                <%= @recipe.time_unit %>
              <% end %>
            </p>
          </div>
        <% end %>
        <div class="medium-8 columns">
          <% unless @recipe.servings.blank? %>
            <p>Servings: <%= @recipe.servings %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <% if @recipe.user == current_user %>
      <div class="medium-5 columns">
        <ul class="button-group">
          <li><%= link_to 'Edit Recipe', edit_recipe_path(@recipe), class: "button small" %></li>
          <li><%= link_to 'Delete Recipe', recipe_path(@recipe), method: :delete,
            data: { confirm: 'Are you sure you want to delete this recipe?' }, class: "button small" %></li>
        </ul>
      </div>
      <div class="medium-7 columns">
    <% else %>
      <div class="medium-12 columns">
    <% end %>
      <% unless @recipe.notes.blank? %>
        <p><em><%= @recipe.notes %></em></p>
      <% end %>
    </div>
  </div>
</div>

<div id="recipe-main-container">
  <div class="row">
    <div class="medium-4 columns">
      <div id="recipe-ingredients-container">
        <h2>Ingredients</h2>
        <p><%= simple_format @recipe.ingredients %></p>
      </div>
    </div>
    <div class="medium-8 columns">
      <div id="recipe-directions-container">
        <h2>Directions</h2>
        <p><%= simple_format @recipe.directions %></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="medium-12 columns">
      <div id="recipe-tags-container">
        <% unless @recipe.tags.count == 0 %>
          <p><strong>Tags:</strong> <%= @recipe.tags.map { |tag| tag.name }.join(', ') %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id="recipe-comments-container">
  <div class="row">
    <div class="medium-12 columns">
      <h2>Comments</h2>
    </div>
  </div>
  <div id="single-comment-container">
    <% if !user_signed_in? && @comments.size == 0 %>
      <p>This recipe currently has no comments. To add a comment, please <%= link_to 'sign in', new_user_session_path %> or <%= link_to 'create an account', new_user_registration_path %>.</p>
    <% end %>
    <% @comments.each do |comment| %>
      <div class="row">
        <div class="medium-12 columns">
          <% unless comment.title.blank? %>
            <h3 class="comment-title"><%= comment.title %></h3>
          <% end %>
        </div>
      </div>
      <div class="row">
        <% if comment.user == current_user %>
          <div class="medium-6 large-8 columns">
        <% else %>
          <div class="medium-12 columns">
        <% end %>
            <div class="comment-body">
              <%= simple_format comment.body %>
            </div>
            <div class="comment-info">
              <em>posted by <%= link_to comment.user.username, user_path(comment.user) %> on <%= comment.created_at.strftime("%F") %></em>
            </div>
          </div>
        <% if comment.user == current_user %>
          <div class="medium-6 large-4 columns">
            <div class="comment-buttons">
              <ul class="button-group">
                <li><%= link_to 'Edit Comment', edit_comment_path(comment), class: "button tiny" %></li>
                <li><%= link_to 'Delete Comment', comment_path(comment), method: :delete,
                  data: { confirm: 'Are you sure you want to delete this comment?' }, class: "button tiny" %></li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? %>
  <div id="new-comment">
    <h3>New Comment</h3>

    <%= form_for [@recipe, @comment] do |f| %>
      <div class="input">
        <%= f.label :title, 'Title (optional)' %>
        <%= f.text_field :title %>
      </div>
      <div class="input">
        <%= f.label :body, 'Comment Text' %>
        <%= f.text_area :body, cols: 30, rows: 5 %>
      </div>
      <div class="submit">
        <%= f.submit 'Add Comment', class: "button tiny" %>
      </div>
    <% end %>
  </div>
<% end %>