config/routes.rb
RecipeBox::Application.routes.draw do
  devise_for :users
  root to: 'pages#welcome'

  resources :recipes do
    resources :comments, shallow: true, except: [:new, :show, :index]
  end

  resources :users, only: :show do
    resources :tags, only: [:index, :create]
    resources :recipes, only: :index
  end

  resources :tags, only: [:show, :edit, :update, :destroy]

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  validates :name, presence: true, uniqueness: { scope: :user_id }

  has_many :recipe_tags, inverse_of: :tag, dependent: :destroy
  has_many :recipes, through: :recipe_tags
  belongs_to :user, inverse_of: :tags

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @tags = Tag.where(user_id: params[:user_id])
    @user = User.find(params[:user_id])
    @tag = Tag.new
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.user = current_user

    if @tag.save
      flash[:notice] = 'Your tag was successfully added.'
      redirect_to user_tags_path(current_user)
    else
      flash[:alert] = 'There was an issue with your tag. Please try again.'
      redirect_to user_tags_path(current_user)
    end
  end

  def edit
    @tag = Tag.find(params[:id])
    authorize_user(@tag)
  end

  def update
    @tag = Tag.find(params[:id])
    authorize_user(@tag)

    if @tag.update(tag_params)
      flash[:notice] = 'Your tag was successfully updated.'
      redirect_to user_tags_path(current_user)
    else
      flash[:alert] = 'There was an issue with your tag. Please try again.'
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    authorize_user(@tag)

    @tag.destroy
    flash[:notice] = 'Your tag was successfully deleted.'
    redirect_to user_tags_path(current_user)
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end

  def authorize_user(tag)
    unless user_signed_in? and (tag.user == current_user)
      raise ActionController::RoutingError.new('The page you requested was not found.')
    end
  end
end

app/views/tags/edit.html.erb
<h2>Edit Tag</h2>

<%= form_for @tag do |f| %>
  <div id="tag-form-input">
    <div class="input">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  </div>
  <div class="row">
    <div class="medium-12 columns">
      <div id="tag-form-button">
        <ul class="button-group">
          <li>
            <div class="submit">
              <%= f.submit 'Update Tag', class: "button small" %>
            </div>
          </li>
          <li><%= link_to 'Back to Tags', user_tags_path(@tag.user), class: "button small" %></li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/tags/index.html.erb
<h1><%= @user.username %>'s Tags</h1>

<div id="tag-intro">
  <p>All tags belonging to <%= link_to @user.username, user_path(@user) %>:</p>
</div>

<% if @user == current_user %>
  <% @tags.each do |tag| %>
    <div class="row">
      <div class="small-4 medium-6 large-8 columns">
        <div class="tag-link">
          <p><%= link_to tag.name, tag_path(tag) %></p>
        </div>
      </div>
      <div class="small-8 medium-6 large-4 columns">
        <div class="tag-buttons">
          <ul class="button-group">
            <li><%= link_to 'Edit Tag', edit_tag_path(tag), class: "button small" %></li>
            <li><%= link_to 'Delete Tag', tag_path(tag), method: :delete,
              data: { confirm: 'Are you sure you want to delete this tag?' }, class: "button small" %></li>
          </ul>
        </div>
      </div>
    </div>
  <% end %>

<% else %>
  <% @tags.each do |tag| %>
    <p><%= link_to tag.name, tag_path(tag) %></p>
  <% end %>
<% end %>

<% if @user == current_user %>
  <h3>New Tag</h3>

  <%= form_for [current_user, @tag] do |f| %>
    <div id="tag-form-input">
      <div class="input">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </div>
    </div>
    <div id="tag-form-button">
      <div class="submit">
        <%= f.submit 'Add Tag', class: "button small" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<div id="tag-intro">
  <p>All recipes tagged with "<%= @tag.name %>" by <%= link_to @tag.user.username, user_path(@tag.user) %>:</p>
</div>

<% if @tag.recipes.count == 0 %>
  <p>No recipes were found for this tag.</p>
<% else %>
  <% @tag.recipes.each do |recipe| %>
    <p><%= link_to recipe.name, recipe_path(recipe) %></p>
  <% end %>
<% end %>

<%= link_to 'Back to Tags', user_tags_path(@tag.user), class: "button small" %>