config/routes.rb
RecipeBox::Application.routes.draw do
  devise_for :users
  root to: 'pages#welcome'

  resources :recipes do
    resources :comments, shallow: true, except: [:new, :show, :index]
  end

  resources :users, only: :show do
    resources :tags, only: [:index, :create]
    resources :recipes, only: :index
  end

  resources :tags, only: [:show, :edit, :update, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "RecipeBox" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name"></li>
        <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
      </ul>
      <section class="top-bar-section">
        <% if user_signed_in? %>
          <ul class="left">
            <li><%= link_to 'All Recipes', recipes_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'My Recipes', user_recipes_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to 'My Tags', user_tags_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to 'Add New Recipe', new_recipe_path %></li>
            <li class="divider"></li>
          </ul>
          <ul class="right">
            <li class="divider"></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul class="left">
            <li><%= link_to 'All Recipes', recipes_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Create New Account', new_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
            <li class="divider"></li>
          </ul>
        <% end %>
      </section>
    </nav>
    <div id="page-content">
      <div class="row">
        <div class="large-12 columns">

          <% flash.each do |name, msg| %>
            <% if msg.is_a?(String) %>
              <div data-alert class="alert-box <%= name == :notice ? "success" : "alert" %>">
                <%= content_tag :div, msg %>
                <a href="#" class="close">&times;</a>
              </div>
            <% end %>
          <% end %>

          <%= yield %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>